task:
    server_url: "http://localhost:9000"
    try_limit: 5
    task_timeout: 120
    pool: "test"
    request_timeout: 100
    num_worker: 4
    exit_when_done: true
    retry_interval: 3
    retry_limit: 5
    log_level: DEBUG
    log_file: log/executor.log
